### PR TITLE
User story 6 add delete function

### PR DESCRIPTION
**Pull request by xoihin**
Hiu Michael,

I have Implemented the following:

```
 User Story 6 As a user, I want to be able to swipe on rows of audio files, and be able to delete, or rename my audio files. 
```

Thanks for reviewing.

Xoi

### CODE REVIEW

**Comment by nerdyverde** [comment]
If there are only two options when swiping each row (rename and delete), then I think that we can get rid of the more button and the UIAlertAction prompt. If you are planning to add additional actions here, then we should create new issues to document those intentions.

**Comment by xoihin** [comment]
Yes.  I would like to add the "Share" feature.  To send audio files using Airdrop.

Created new issue.

**Comment by xoihin** [comment]
Hi Michael,

I've implemented the followings:

```
 Localized all texts.
 Added audio duration on table view.
 Upgraded app to use Xcode 7.   (Just downloaded Xcode 7.1)
```

Cheers,

Xoi

**Comment by nerdyverde** [comment]
The changes look good Xoi!

**Comment by xoihin** [comment]
Thanks, Michael.  I have been busy with my other job lately.  I am still on schedule though on this capstone project.

**Comment by nerdyverde** [comment]
No problem Xoi. I was just reviewing the state of the project for our call later today and I realized that I forgot to merge your changes after reviewing them.

**Pull request merged**
