### PR TITLE
User story 3 play audio files

### PR DESCRIPTION
**Pull request by xoihin**
Includes:

User story 1 - List all audio files from document directory on table view.
User story 2 - Record audio by a light shake on the iOS device.  Shake again to save recording.
User story 3 - Playback of audio files.

### CODE REVIEW

**Comment by xoihin** [comment]
Hi Michael,

Please see descriptions above for details on this PR.

Thanks,

Xoi

**Comment by nerdyverde** [comment]
I personally find it a little confusing having separate play and pause buttons. Since they are mutually exclusive (pause is inactive whenever the audio isn't playing, play is inactive whenever the audio is playing), it seems to me that they should be combined into a single button which reflects this state change.

It seems to me that the user should be able to see at a glance how long each audio recording is as well. Given that you're currently only showing the audio title in the table cell, it shouldn't be too crowded if you add information about audio length.

Have you considered adding information to the toolbar which indicates play head progress? It's nice to be able to reset progress, but I would also like to know at a glance how far along in the audio file the current play is.

**Comment by xoihin** [comment]
I think that having a play and pause as one button is really a personal preference.  Some users still prefer  
them as separate buttons as long as the control is not confusing.

I created a new issue to show audio duration where possible.

I added another issue to have a slider to show playback progress.

**Comment by nerdyverde** [comment]
Sounds good.

**Pull request merged**
